In [5]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
# ==========================================
# MASTER PRODUCT DATABASE - WINGS GROUP
# Trade Marketing Data Analyst Project
# ==========================================


import pandas as pd
import random


# ==========================================
# 1. RAW PRODUCT DATA
# ==========================================

products = [

    # ======================
    # FABRIC CARE
    # ======================

    ["SoKlin","SoKlin Detergent Powder","Fabric Care","Powder Detergent"],
    ["SoKlin","SoKlin Liquid Detergent","Fabric Care","Liquid Detergent"],
    ["SoKlin","SoKlin Softener","Fabric Care","Fabric Softener"],
    ["SoKlin","SoKlin Pewangi","Fabric Care","Fabric Fragrance"],
    ["Daia","Daia Detergent Powder","Fabric Care","Powder Detergent"],
    ["Boom","Boom Detergent","Fabric Care","Powder Detergent"],
    ["Ekonomi","Ekonomi Cream Detergent","Fabric Care","Cream Detergent"],
    ["Ekonomi","Ekonomi Liquid Detergent","Fabric Care","Liquid Detergent"],
    ["So Soft","So Soft Detergent","Fabric Care","Powder Detergent"],
    ["Wings","Wings Detergent","Fabric Care","Powder Detergent"],


    # ======================
    # HOME CARE
    # ======================

    ["Mama Lemon","Mama Lemon Dishwash","Home Care","Dishwashing Liquid"],
    ["Ekonomi","Ekonomi Dishwash","Home Care","Dishwashing Liquid"],
    ["WPC","WPC Toilet Cleaner","Home Care","Toilet Cleaner"],
    ["Supersol","Supersol Floor Cleaner","Home Care","Floor Cleaner"],
    ["Cling","Cling Glass Cleaner","Home Care","Glass Cleaner"],
    ["Fresly","Fresly Air Freshener","Home Care","Air Freshener"],
    ["WIZ","WIZ Disinfectant","Home Care","Disinfectant"],


    # ======================
    # PERSONAL CARE
    # ======================

    ["GIV","GIV Soap","Personal Care","Bath Soap"],
    ["GIV","GIV White Soap","Personal Care","Bath Soap"],
    ["Nuvo","Nuvo Soap","Personal Care","Bath Soap"],
    ["Ciptadent","Ciptadent Toothpaste","Personal Care","Toothpaste"],
    ["Kodomo","Kodomo Toothpaste","Personal Care","Toothpaste"],
    ["Kodomo","Kodomo Shampoo","Personal Care","Shampoo"],
    ["Systema","Systema Toothbrush","Personal Care","Toothbrush"],
    ["Emeron","Emeron Shampoo","Personal Care","Shampoo"],
    ["Zinc","Zinc Shampoo","Personal Care","Shampoo"],
    ["Serasoft","Serasoft Shampoo","Personal Care","Shampoo"],
    ["Posh","Posh Perfume","Personal Care","Perfume"],
    ["ProGuard","ProGuard Deodorant","Personal Care","Deodorant"],
    ["Hers Protex","Hers Protex Feminine Care","Personal Care","Feminine Care"],
    ["Baby Happy","Baby Happy Diaper","Baby Care","Diaper"],


    # ======================
    # FOOD
    # ======================

    ["Mie Sedaap","Mie Sedaap Goreng","Food","Instant Noodle"],
    ["Mie Sedaap","Mie Sedaap Soto","Food","Instant Noodle"],
    ["Mie Sedaap","Mie Sedaap Cup","Food","Cup Noodle"],
    ["Mie Sedaap","Ramen Yes","Food","Instant Noodle"],
    ["Sedaap","Kecap Sedaap","Food","Soy Sauce"],
    ["Sedaap","Bumbu Kaldu Sedaap","Food","Seasoning"],
    ["Eko Mie","Eko Mie","Food","Instant Noodle"],
    ["So Yumie","So Yumie Instant Noodle","Food","Instant Noodle"],


    # ======================
    # BEVERAGE
    # ======================

    ["Floridina","Floridina Orange Drink","Beverage","Fruit Drink"],
    ["Teh Javana","Teh Javana","Beverage","Tea Drink"],
    ["Teajus","Teajus Powder Drink","Beverage","Powder Drink"],
    ["Jas Jus","Jas Jus Powder Drink","Beverage","Powder Drink"],
    ["Ale-Ale","Ale-Ale Fruit Drink","Beverage","Fruit Drink"],
    ["Golda Coffee","Golda Coffee","Beverage","Coffee Drink"],
    ["TOP Coffee","TOP Coffee","Beverage","Coffee Drink"],
    ["Neo Coffee","Neo Coffee","Beverage","Coffee Drink"],
    ["Isoplus","Isoplus Isotonic Drink","Beverage","Isotonic Drink"],
    ["Milku","Milku Milk Drink","Beverage","Milk Drink"],
    ["Aquviva","Aquviva Mineral Water","Beverage","Mineral Water"],
    ["Segar Dingin","Segar Dingin","Beverage","Herbal Drink"],


    # ======================
    # SNACK
    # ======================

    ["Potabee","Potato Snack","Snack","Potato Chips"],
    ["Japota","Potato Chips","Snack","Potato Chips"],
    ["Krisbee","Krisbee Snack","Snack","Snack"],
    ["Haku","Haku Ice Cream","Snack","Ice Cream"],
    ["Waku Waku","Waku Waku Ice Cream","Snack","Ice Cream"],
    ["Frost Bite","Frost Bite Ice Cream","Snack","Ice Cream"],
    ["J-Cone","J-Cone Ice Cream Cone","Snack","Ice Cream"]
]


# ==========================================
# 2. CREATE DATAFRAME
# ==========================================

df = pd.DataFrame(
    products,
    columns=[
        "brand",
        "product_name",
        "category",
        "sub_category"
    ]
)



# ==========================================
# 3. GENERATE SKU ID
# ==========================================

sku_counter = {}

def create_sku(row):

    brand = (
        row["brand"]
        .upper()
        .replace(" ","")
    )

    product = (
        row["product_name"]
        .upper()
    )


    # kode produk
    if "MIE" in product:
        code="MIE"

    elif "DETERGENT" in product:
        code="DET"

    elif "SOAP" in product:
        code="SOAP"

    elif "DRINK" in product:
        code="DRINK"

    elif "COFFEE" in product:
        code="COFF"

    elif "SHAMPOO" in product:
        code="SHAMP"

    elif "ICE" in product:
        code="ICE"

    else:
        code="GEN"



    key = f"{brand}-{code}"

    if key not in sku_counter:
        sku_counter[key]=1
    else:
        sku_counter[key]+=1


    return f"{key}-{sku_counter[key]:03d}"



df["sku_id"] = df.apply(
    create_sku,
    axis=1
)



# ==========================================
# 4. GENERATE PACK SIZE
# ==========================================

def create_pack(category):

    if category=="Food":
        return random.choice([
            "75 gr",
            "85 gr",
            "90 gr",
            "120 gr"
        ])

    elif category=="Beverage":
        return random.choice([
            "250 ml",
            "350 ml",
            "500 ml"
        ])

    elif category=="Fabric Care":
        return random.choice([
            "450 gr",
            "770 gr",
            "800 ml"
        ])

    elif category=="Personal Care":
        return random.choice([
            "70 gr",
            "80 gr",
            "100 ml"
        ])

    elif category=="Snack":
        return random.choice([
            "50 gr",
            "100 gr"
        ])

    else:
        return random.choice([
            "500 ml",
            "800 ml"
        ])



df["pack_size"] = df["category"].apply(
    create_pack
)



# ==========================================
# 5. GENERATE UNIT PRICE
# ==========================================


def create_price(category):

    if category=="Food":
        return random.randint(
            2500,5000
        )

    elif category=="Beverage":
        return random.randint(
            3000,8000
        )

    elif category=="Fabric Care":
        return random.randint(
            10000,30000
        )

    elif category=="Personal Care":
        return random.randint(
            3000,20000
        )

    elif category=="Snack":
        return random.randint(
            5000,15000
        )

    else:
        return random.randint(
            7000,25000
        )



df["unit_price"] = df["category"].apply(
    create_price
)



# ==========================================
# 6. FINAL COLUMN ORDER
# ==========================================

df = df[
    [
        "sku_id",
        "product_name",
        "brand",
        "category",
        "sub_category",
        "pack_size",
        "unit_price"
    ]
]



# ==========================================
# 7. EXPORT FILE
# ==========================================


df.to_csv(
    "dim_product.csv",
    index=False
)


df.to_excel(
    "dim_product.xlsx",
    index=False
)



# ==========================================
# 8. SHOW DATA
# ==========================================

print(df.head(10))

print("\nJumlah Produk:",
      len(df))

            sku_id              product_name    brand     category  \
0   SOKLIN-DET-001   SoKlin Detergent Powder   SoKlin  Fabric Care
1   SOKLIN-DET-002   SoKlin Liquid Detergent   SoKlin  Fabric Care
2   SOKLIN-GEN-001           SoKlin Softener   SoKlin  Fabric Care
3   SOKLIN-GEN-002            SoKlin Pewangi   SoKlin  Fabric Care
4     DAIA-DET-001     Daia Detergent Powder     Daia  Fabric Care
5     BOOM-DET-001            Boom Detergent     Boom  Fabric Care
6  EKONOMI-DET-001   Ekonomi Cream Detergent  Ekonomi  Fabric Care
7  EKONOMI-DET-002  Ekonomi Liquid Detergent  Ekonomi  Fabric Care
8   SOSOFT-DET-001         So Soft Detergent  So Soft  Fabric Care
9    WINGS-DET-001           Wings Detergent    Wings  Fabric Care

       sub_category pack_size  unit_price
0  Powder Detergent    770 gr       24833
1  Liquid Detergent    450 gr       29669
2   Fabric Softener    800 ml       12420
3  Fabric Fragrance    450 gr       18619
4  Powder Detergent    800 ml       21205
5  Powder Detergent    800 ml       20700
6   Cream Detergent    800 ml       10256
7  Liquid Detergent    800 ml       15181
8  Powder Detergent    450 gr       12238
9  Powder Detergent    450 gr       17257

Jumlah Produk: 58

In [11]:
# ==========================================
# DIM OUTLET DATABASE - WINGS GROUP
# Trade Marketing Analytics Project
# Total Outlet = 1200
# ==========================================


import pandas as pd
import random


# Untuk hasil konsisten
random.seed(42)



# ==========================================
# 1. MASTER STORE / CHAIN
# ==========================================

store_master = [

    # Modern Trade
    {
        "chain_name":"Indomaret",
        "channel":"Modern Trade",
        "outlet_type":"Minimarket",
        "total":220
    },

    {
        "chain_name":"Alfamart",
        "channel":"Modern Trade",
        "outlet_type":"Minimarket",
        "total":220
    },

    {
        "chain_name":"Alfamidi",
        "channel":"Modern Trade",
        "outlet_type":"Minimarket",
        "total":90
    },


    {
        "chain_name":"Super Indo",
        "channel":"Modern Trade",
        "outlet_type":"Supermarket",
        "total":70
    },


    {
        "chain_name":"Hypermart",
        "channel":"Modern Trade",
        "outlet_type":"Hypermarket",
        "total":40
    },


    {
        "chain_name":"Lotte Mart",
        "channel":"Modern Trade",
        "outlet_type":"Hypermarket",
        "total":40
    },


    {
        "chain_name":"Transmart",
        "channel":"Modern Trade",
        "outlet_type":"Hypermarket",
        "total":40
    },


    {
        "chain_name":"AEON",
        "channel":"Modern Trade",
        "outlet_type":"Supermarket",
        "total":25
    },


    {
        "chain_name":"Ranch Market",
        "channel":"Modern Trade",
        "outlet_type":"Supermarket",
        "total":15
    },


    # Wholesale

    {
        "chain_name":"Grosir Nasional",
        "channel":"Wholesale",
        "outlet_type":"Grosir",
        "total":150
    },


    {
        "chain_name":"Distributor Center",
        "channel":"Wholesale",
        "outlet_type":"Distributor",
        "total":100
    },


    {
        "chain_name":"Cash & Carry",
        "channel":"Wholesale",
        "outlet_type":"Wholesale Store",
        "total":40
    },


    # E-Commerce

    {
        "chain_name":"Shopee Official Store",
        "channel":"E-Commerce",
        "outlet_type":"Marketplace",
        "total":35
    },


    {
        "chain_name":"Tokopedia Official Store",
        "channel":"E-Commerce",
        "outlet_type":"Marketplace",
        "total":35
    },


    {
        "chain_name":"TikTok Shop Official Store",
        "channel":"E-Commerce",
        "outlet_type":"Marketplace",
        "total":35
    },


    {
        "chain_name":"Lazada Official Store",
        "channel":"E-Commerce",
        "outlet_type":"Marketplace",
        "total":15
    },


    {
        "chain_name":"Blibli Official Store",
        "channel":"E-Commerce",
        "outlet_type":"Marketplace",
        "total":15
    }

]



# ==========================================
# 2. MASTER LOCATION
# ==========================================


locations = [

    # =====================
    # JAWA
    # =====================

    ["Jakarta","DKI Jakarta","Jawa"],
    ["Bogor","Jawa Barat","Jawa"],
    ["Depok","Jawa Barat","Jawa"],
    ["Bekasi","Jawa Barat","Jawa"],
    ["Bandung","Jawa Barat","Jawa"],
    ["Cirebon","Jawa Barat","Jawa"],

    ["Semarang","Jawa Tengah","Jawa"],
    ["Solo","Jawa Tengah","Jawa"],
    ["Yogyakarta","DI Yogyakarta","Jawa"],

    ["Surabaya","Jawa Timur","Jawa"],
    ["Malang","Jawa Timur","Jawa"],
    ["Sidoarjo","Jawa Timur","Jawa"],
    ["Kediri","Jawa Timur","Jawa"],



    # =====================
    # SUMATERA
    # =====================

    ["Medan","Sumatera Utara","Sumatera"],
    ["Binjai","Sumatera Utara","Sumatera"],

    ["Padang","Sumatera Barat","Sumatera"],

    ["Pekanbaru","Riau","Sumatera"],
    ["Batam","Kepulauan Riau","Sumatera"],

    ["Jambi","Jambi","Sumatera"],

    ["Palembang","Sumatera Selatan","Sumatera"],
    ["Prabumulih","Sumatera Selatan","Sumatera"],

    ["Bandar Lampung","Lampung","Sumatera"],



    # =====================
    # KALIMANTAN
    # =====================

    ["Pontianak","Kalimantan Barat","Kalimantan"],
    ["Banjarmasin","Kalimantan Selatan","Kalimantan"],
    ["Banjarbaru","Kalimantan Selatan","Kalimantan"],

    ["Balikpapan","Kalimantan Timur","Kalimantan"],
    ["Samarinda","Kalimantan Timur","Kalimantan"],

    ["Palangkaraya","Kalimantan Tengah","Kalimantan"],



    # =====================
    # SULAWESI
    # =====================

    ["Makassar","Sulawesi Selatan","Sulawesi"],
    ["Parepare","Sulawesi Selatan","Sulawesi"],

    ["Manado","Sulawesi Utara","Sulawesi"],

    ["Palu","Sulawesi Tengah","Sulawesi"],

    ["Kendari","Sulawesi Tenggara","Sulawesi"],



    # =====================
    # BALI & NUSA TENGGARA
    # =====================

    ["Denpasar","Bali","Bali-Nusa"],

    ["Mataram","Nusa Tenggara Barat","Bali-Nusa"],

    ["Kupang","Nusa Tenggara Timur","Bali-Nusa"],



    # =====================
    # MALUKU
    # =====================

    ["Ambon","Maluku","Maluku"],



    # =====================
    # PAPUA (HANYA KOTA UTAMA)
    # =====================

    ["Jayapura","Papua","Papua"]

]



# ==========================================
# 3. GENERATE DATA
# ==========================================


outlets = []

counter = 1


for store in store_master:


    for i in range(store["total"]):


        # Jika online
        if store["channel"] == "E-Commerce":

            city = "Online"
            province = "National"
            region = "Indonesia"


            outlet_name = store["chain_name"]



        else:

            loc = random.choice(locations)


            city = loc[0]
            province = loc[1]
            region = loc[2]


            outlet_name = (
                store["chain_name"]
                +" "
                +city
                +" "
                +str(i+1)
            )



        tier = random.choices(
            ["A","B","C"],
            weights=[50,35,15]
        )[0]



        outlets.append(

            [

                f"OUT{counter:06d}",

                outlet_name,

                store["channel"],

                store["outlet_type"],

                store["chain_name"],

                region,

                province,

                city,

                tier,

                "Active"

            ]

        )


        counter += 1




# ==========================================
# 4. CREATE DATAFRAME
# ==========================================


dim_outlet = pd.DataFrame(

    outlets,

    columns=[

        "outlet_id",

        "outlet_name",

        "channel",

        "outlet_type",

        "chain_name",

        "region",

        "province",

        "city",

        "tier",

        "status"

    ]

)



# ==========================================
# 5. VALIDATION
# ==========================================


print(dim_outlet.head())


print(
    "\nTotal Outlet:",
    len(dim_outlet)
)



print(
    "\nDistribusi Channel:"
)

print(
    dim_outlet["channel"].value_counts()
)



# ==========================================
# 6. EXPORT
# ==========================================


dim_outlet.to_csv(

    "dim_outlet_wings.csv",

    index=False

)


print(
    "\nFile berhasil dibuat: dim_outlet_wings.csv"
)

   outlet_id               outlet_name       channel outlet_type chain_name  \
0  OUT000001          Indomaret Solo 1  Modern Trade  Minimarket  Indomaret
1  OUT000002         Indomaret Batam 2  Modern Trade  Minimarket  Indomaret
2  OUT000003    Indomaret Yogyakarta 3  Modern Trade  Minimarket  Indomaret
3  OUT000004       Indomaret Mataram 4  Modern Trade  Minimarket  Indomaret
4  OUT000005  Indomaret Palangkaraya 5  Modern Trade  Minimarket  Indomaret

       region             province          city tier  status
0        Jawa          Jawa Tengah          Solo    A  Active
1    Sumatera       Kepulauan Riau         Batam    A  Active
2        Jawa        DI Yogyakarta    Yogyakarta    B  Active
3   Bali-Nusa  Nusa Tenggara Barat       Mataram    A  Active
4  Kalimantan    Kalimantan Tengah  Palangkaraya    A  Active

Total Outlet: 1185

Distribusi Channel:
channel
Modern Trade    760
Wholesale       290
E-Commerce      135
Name: count, dtype: int64

File berhasil dibuat: dim_outlet_wings.csv

In [14]:
# ==========================================
# DIM DATE DATABASE
# Trade Marketing Analytics Project
# Period: 2023 - 2026
# ==========================================


import pandas as pd



# ==========================================
# 1. CREATE DATE RANGE
# ==========================================

date_range = pd.date_range(
    start="2023-01-01",
    end="2026-12-31",
    freq="D"
)



# ==========================================
# 2. CREATE DATAFRAME
# ==========================================

dim_date = pd.DataFrame(
    {
        "date": date_range
    }
)



# ==========================================
# 3. CREATE DATE ID
# ==========================================

dim_date["date_id"] = (
    dim_date["date"]
    .dt.strftime("%Y%m%d")
)



# ==========================================
# 4. CREATE MONTH
# ==========================================

dim_date["month"] = (
    dim_date["date"]
    .dt.month
)



# ==========================================
# 5. CREATE QUARTER
# ==========================================

dim_date["quarter"] = (
    "Q"
    +
    dim_date["date"]
    .dt.quarter
    .astype(str)
)



# ==========================================
# 6. CREATE YEAR
# ==========================================

dim_date["year"] = (
    dim_date["date"]
    .dt.year
)



# ==========================================
# 7. REORDER COLUMN
# ==========================================

dim_date = dim_date[
    [
        "date_id",
        "date",
        "month",
        "quarter",
        "year"
    ]
]



# ==========================================
# 8. VALIDATION
# ==========================================


print(dim_date.head())


print("\nData terakhir:")
print(dim_date.tail())


print(
    "\nTotal Date:",
    len(dim_date)
)



# ==========================================
# 9. EXPORT
# ==========================================


dim_date.to_csv(
    "dim_date.csv",
    index=False
)


print(
    "\nFile berhasil dibuat: dim_date.csv"
)

    date_id       date  month quarter  year
0  20230101 2023-01-01      1      Q1  2023
1  20230102 2023-01-02      1      Q1  2023
2  20230103 2023-01-03      1      Q1  2023
3  20230104 2023-01-04      1      Q1  2023
4  20230105 2023-01-05      1      Q1  2023

Data terakhir:
       date_id       date  month quarter  year
1456  20261227 2026-12-27     12      Q4  2026
1457  20261228 2026-12-28     12      Q4  2026
1458  20261229 2026-12-29     12      Q4  2026
1459  20261230 2026-12-30     12      Q4  2026
1460  20261231 2026-12-31     12      Q4  2026

Total Date: 1461

File berhasil dibuat: dim_date.csv

In [16]:
!pip install tqdm

Collecting tqdm
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\program files\python310\lib\site-packages (from tqdm) (0.4.6)
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
Installing collected packages: tqdm
Successfully installed tqdm-4.70.1

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
df = pd.read_csv('fact_sales_wings.csv')

df.head()

,transaction_id,date_id,outlet_id,sku_id,quantity,gross_sales,discount,net_sales
0,TRX000000001,20260131,OUT000553,MIESEDAAP-MIE-003,38,228000,25844,202156
1,TRX000000002,20261230,OUT000107,NEOCOFFEE-COFF-001,16,40000,5284,34716
2,TRX000000003,20250510,OUT000780,SOKLIN-GEN-001,860,12900000,2571053,10328947
3,TRX000000004,20260718,OUT000271,SOKLIN-GEN-001,144,2160000,116595,2043405
4,TRX000000005,20260204,OUT000213,SOKLIN-GEN-002,134,1206000,136293,1069707

In [26]:
# =====================================================
# FACT PROMOTION GENERATOR
# WINGS GROUP TRADE MARKETING ANALYTICS
#
# Target : ~80.000 promotion rows
# Period : 2023 - 2026
# =====================================================


import pandas as pd
import numpy as np
import random
from datetime import timedelta


# =====================================================
# RANDOM SEED
# =====================================================

random.seed(42)
np.random.seed(42)



# =====================================================
# LOAD MASTER DATA
# =====================================================


product = pd.read_csv(
    "dim_product.csv"
)


outlet = pd.read_csv(
    "dim_outlet.csv"
)


date = pd.read_csv(
    "dim_date.csv"
)



# =====================================================
# PARAMETER
# =====================================================


TOTAL_PROMOTION = 80000



# =====================================================
# SKU PROMOTION PROBABILITY
# =====================================================


category_probability = {

    "Food":0.80,

    "Beverage":0.75,

    "Fabric Care":0.70,

    "Snack":0.50,

    "Home Care":0.50,

    "Personal Care":0.40,

    "Baby Care":0.30

}



product["promo_probability"] = (
    product["category"]
    .map(category_probability)
)



# =====================================================
# PROMO TYPE BASED ON CHANNEL
# =====================================================


promo_rules = {


    "Modern Trade":[

        "Price Discount",
        "Bundle Promo",
        "Display Promo",
        "Sampling"

    ],


    "Wholesale":[

        "Trade Discount",
        "Bulk Discount",
        "Carton Promo"

    ],


    "E-Commerce":[

        "Flash Sale",
        "Voucher",
        "Cashback",
        "Free Shipping",
        "Campaign Event"

    ]

}



# =====================================================
# DISCOUNT RULE
# =====================================================


def generate_discount(channel):


    if channel == "Modern Trade":

        return random.randint(
            5,
            20
        )


    elif channel == "Wholesale":

        return random.randint(
            10,
            30
        )


    else:

        return random.randint(
            15,
            50
        )



# =====================================================
# PROMO DURATION
# =====================================================


def generate_duration(promo_type):


    if promo_type == "Flash Sale":

        return random.randint(
            1,
            3
        )


    elif promo_type in [
        "Voucher",
        "Cashback"
    ]:

        return random.randint(
            3,
            14
        )


    elif promo_type in [
        "Campaign Event",
        "Display Promo"
    ]:

        return random.randint(
            14,
            45
        )


    else:

        return random.randint(
            14,
            30
        )



# =====================================================
# PROMO BUDGET
# =====================================================


def generate_budget(channel):


    if channel == "Modern Trade":

        return random.randint(
            5000000,
            100000000
        )


    elif channel == "Wholesale":

        return random.randint(
            10000000,
            250000000
        )


    else:

        return random.randint(
            5000000,
            500000000
        )



# =====================================================
# GENERATE PROMOTION
# =====================================================


promotion=[]



promo_counter=1



while len(promotion) < TOTAL_PROMOTION:


    # -------------------------
    # Select Product
    # -------------------------

    sku = product.sample(
        1,
        weights="promo_probability"
    ).iloc[0]



    # -------------------------
    # Select Outlet
    # -------------------------

    store = outlet.sample(
        1
    ).iloc[0]



    channel = store["channel"]



    # -------------------------
    # Promo Type
    # -------------------------

    promo_type = random.choice(
        promo_rules[channel]
    )



    # -------------------------
    # Date
    # -------------------------

    start = pd.to_datetime(
        date.sample(1)["date"].values[0]
    )


    duration = generate_duration(
        promo_type
    )


    end = start + timedelta(
        days=duration
    )


    # limit sampai 2026
    if end.year > 2026:
        continue



    # -------------------------
    # Seasonal Boost
    # -------------------------

    if start.month in [3,4]:

        if sku["category"] in [
            "Food",
            "Beverage",
            "Fabric Care"
        ]:

            promo_type = (
                "Ramadan Campaign"
            )



    # -------------------------
    # Create Row
    # -------------------------


    promotion.append(

        [

            f"PROMO{promo_counter:06d}",

            sku["sku_id"],

            store["outlet_id"],

            promo_type,

            start.date(),

            end.date(),

            generate_discount(
                channel
            ),

            generate_budget(
                channel
            )

        ]

    )


    promo_counter += 1





# =====================================================
# CREATE DATAFRAME
# =====================================================


fact_promotion = pd.DataFrame(

    promotion,

    columns=[

        "promotion_id",

        "sku_id",

        "outlet_id",

        "promo_type",

        "start_date",

        "end_date",

        "discount_percentage",

        "promo_budget"

    ]

)



# =====================================================
# VALIDATION
# =====================================================


print(
    fact_promotion.head()
)


print("\nTotal Promotion:")
print(
    len(fact_promotion)
)



print("\nPromo Type:")
print(
    fact_promotion["promo_type"]
    .value_counts()
)



# =====================================================
# EXPORT
# =====================================================


fact_promotion.to_csv(

    "fact_promotion_wings.csv",

    index=False

)



print(
    "\nFile berhasil dibuat:"
)

print(
    "fact_promotion_wings.csv"
)

  promotion_id             sku_id  outlet_id      promo_type  start_date  \
0  PROMO000001    SYSTEMA-GEN-001  OUT000320  Price Discount  2024-07-13
1  PROMO000002    EKONOMI-GEN-001  OUT000326    Bundle Promo  2026-07-31
2  PROMO000003  ISOPLUS-DRINK-001  OUT000897    Carton Promo  2023-12-07
3  PROMO000004    EKONOMI-GEN-001  OUT000148  Price Discount  2026-07-25
4  PROMO000005  MIESEDAAP-GEN-001  OUT000198    Bundle Promo  2026-05-26

     end_date  discount_percentage  promo_budget
0  2024-07-27                   13      37868828
1  2026-08-18                    8      95825067
2  2023-12-23                   28     123258777
3  2026-08-08                    7      34345092
4  2026-06-25                    5      80329037

Total Promotion:
80000

Promo Type:
promo_type
Sampling            11420
Price Discount      11398
Bundle Promo        11374
Display Promo       11347
Ramadan Campaign     8814
Carton Promo         5900
Bulk Discount        5899
Trade Discount       5782
Flash Sale           1634
Voucher              1634
Campaign Event       1601
Cashback             1599
Free Shipping        1598
Name: count, dtype: int64

File berhasil dibuat:
fact_promotion_wings.csv

In [1]:
# ======================================================
# FACT SALES GENERATOR OPTIMIZED
# WINGS GROUP TRADE MARKETING ANALYTICS
#
# INPUT:
# dim_product.csv
# dim_outlet.csv
# dim_date.csv
# fact_promotion.csv
#
# OUTPUT:
# fact_sales.csv
#
# ROW TARGET:
# 1,435,389
# ======================================================


import pandas as pd
import numpy as np
import random
from tqdm import tqdm



# ======================================================
# RANDOM SEED
# ======================================================

random.seed(42)
np.random.seed(42)



# ======================================================
# LOAD MASTER DATA
# ======================================================


product = pd.read_csv(
    "dim_product.csv"
)


outlet = pd.read_csv(
    "dim_outlet.csv"
)


date = pd.read_csv(
    "dim_date.csv"
)


promotion = pd.read_csv(
    "fact_promotion.csv"
)



print("MASTER DATA LOADED")

print(
    "Product:",
    product.shape
)

print(
    "Outlet:",
    outlet.shape
)

print(
    "Date:",
    date.shape
)

print(
    "Promotion:",
    promotion.shape
)



# ======================================================
# PREP PRODUCT
# ======================================================


category_weight = {

    "Food":0.85,

    "Beverage":0.80,

    "Fabric Care":0.70,

    "Snack":0.65,

    "Home Care":0.60,

    "Personal Care":0.55,

    "Baby Care":0.45

}


product["sales_weight"] = (

    product["category"]

    .map(category_weight)

    .fillna(0.5)

)



# ======================================================
# PREP OUTLET
# ======================================================


tier_multiplier = {

    "A":2.0,

    "B":1.0,

    "C":0.5

}



outlet["sales_multiplier"] = (

    outlet["tier"]

    .map(tier_multiplier)

    .fillna(1)

)



# ======================================================
# PREP DATE
# ======================================================


date["date"] = pd.to_datetime(
    date["date"]
)



# ======================================================
# CREATE PROMO LOOKUP
# ======================================================

print("Creating promotion lookup...")

promotion["start_date"] = pd.to_datetime(
    promotion["start_date"]
)


promotion["end_date"] = pd.to_datetime(
    promotion["end_date"]
)



promo_lookup = {}



for _, row in promotion.iterrows():


    promo_dates = pd.date_range(

        start=row["start_date"],

        end=row["end_date"],

        freq="D"

    )


    for d in promo_dates:


        key = (

            row["sku_id"],

            row["outlet_id"],

            d.strftime("%Y-%m-%d")

        )


        promo_lookup[key] = (

            row["discount_percentage"]

        )



print(
    "Promo lookup size:",
    len(promo_lookup)
)



# ======================================================
# PARAMETER
# ======================================================


TOTAL_ROWS = 1435389


CHUNK_SIZE = 100000



# ======================================================
# GENERATE FUNCTION
# ======================================================


def generate_sales(batch, start_id):


    # ----------------------------
    # Sampling
    # ----------------------------


    date_sample = date.sample(

        batch,

        replace=True

    )


    outlet_sample = outlet.sample(

        batch,

        replace=True

    )


    product_sample = product.sample(

        batch,

        replace=True,

        weights=product["sales_weight"]

    )



    df = pd.DataFrame()



    # ----------------------------
    # Transaction ID
    # ----------------------------


    df["transaction_id"] = [

        f"TRX{i:09d}"

        for i in range(

            start_id,

            start_id + batch

        )

    ]



    # ----------------------------
    # Keys
    # ----------------------------


    df["date_id"] = (

        date_sample["date_id"]

        .values

    )


    df["outlet_id"] = (

        outlet_sample["outlet_id"]

        .values

    )


    df["sku_id"] = (

        product_sample["sku_id"]

        .values

    )



    # ----------------------------
    # Base Quantity
    # ----------------------------


    quantity = []


    for channel, multiplier in zip(

        outlet_sample["channel"],

        outlet_sample["sales_multiplier"]

    ):


        if channel == "Modern Trade":

            qty = random.randint(
                10,
                150
            )


        elif channel == "Wholesale":

            qty = random.randint(
                50,
                800
            )


        else:

            qty = random.randint(
                1,
                20
            )



        quantity.append(

            int(qty * multiplier)

        )



    df["quantity"] = quantity



    # ----------------------------
    # Promo Checking
    # ----------------------------


    discounts = []

    promo_multiplier = []



    for sku, outlet_id, trx_date in zip(

        df["sku_id"],

        df["outlet_id"],

        date_sample["date"]

    ):


        key = (

            sku,

            outlet_id,

            trx_date.strftime("%Y-%m-%d")

        )


        if key in promo_lookup:


            discounts.append(

                promo_lookup[key]

            )


            promo_multiplier.append(

                random.uniform(
                    1.3,
                    2.0
                )

            )


        else:


            discounts.append(

                random.randint(
                    0,
                    5
                )

            )


            promo_multiplier.append(

                1

            )



    df["quantity"] = (

        df["quantity"]

        *

        promo_multiplier

    ).astype(int)



    df["discount_percentage"] = discounts



    # ----------------------------
    # Seasonal Effect
    # ----------------------------


    months = (

        date_sample["date"]

        .dt.month

    )


    seasonal = np.where(

        months.isin([3,4]),

        1.3,

        1

    )


    df["quantity"] = (

        df["quantity"]

        *

        seasonal

    ).astype(int)



    # ----------------------------
    # Sales Calculation
    # ----------------------------


    price = (

        product_sample["unit_price"]

        .values

    )



    df["gross_sales"] = (

        df["quantity"]

        *

        price

    )



    df["discount"] = (

        df["gross_sales"]

        *

        df["discount_percentage"]

        /

        100

    ).astype(int)



    df["net_sales"] = (

        df["gross_sales"]

        -

        df["discount"]

    )



    df.drop(

        columns=[

            "discount_percentage"

        ],

        inplace=True

    )


    return df



# ======================================================
# EXPORT
# ======================================================


output_file = "fact_sales.csv"


generated = 0


first_write = True



with tqdm(

    total=TOTAL_ROWS

) as bar:



    while generated < TOTAL_ROWS:



        batch = min(

            CHUNK_SIZE,

            TOTAL_ROWS - generated

        )



        sales = generate_sales(

            batch,

            generated + 1

        )



        sales.to_csv(

            output_file,

            mode="a",

            header=first_write,

            index=False

        )



        first_write = False


        generated += batch


        bar.update(batch)



print("==============================")
print("FACT SALES SELESAI")
print("TOTAL ROW:", generated)
print("FILE:", output_file)
print("==============================")

MASTER DATA LOADED
Product: (58, 7)
Outlet: (1185, 10)
Date: (1461, 5)
Promotion: (80000, 8)
Creating promotion lookup...
Promo lookup size: 1842231

100%|██████████| 1435389/1435389 [00:29<00:00, 49082.98it/s]

==============================
FACT SALES SELESAI
TOTAL ROW: 1435389
FILE: fact_sales.csv
==============================

In [2]:
df = pd.read_csv('fact_sales.csv')

df.head()

,transaction_id,date_id,outlet_id,sku_id,quantity,gross_sales,discount,net_sales
0,TRX000000001,20260131,OUT000553,HERSPROTEX-GEN-001,38,380000,19000,361000
1,TRX000000002,20261230,OUT000107,CLING-GEN-001,16,192000,1920,190080
2,TRX000000003,20250510,OUT000780,SEDAAP-GEN-002,662,1986000,59580,1926420
3,TRX000000004,20260718,OUT000271,WINGS-DET-001,144,1152000,57600,1094400
4,TRX000000005,20260204,OUT000213,BOOM-DET-001,134,938000,18760,919240

In [3]:
# =====================================================
# FACT DIGITAL CAMPAIGN GENERATOR
# WINGS GROUP TRADE MARKETING ANALYTICS
#
# Rows : 50,000
#
# =====================================================


import pandas as pd
import numpy as np
import random
from datetime import timedelta



# =====================================================
# RANDOM SEED
# =====================================================

random.seed(42)
np.random.seed(42)



# =====================================================
# LOAD MASTER
# =====================================================


product = pd.read_csv(
    "dim_product.csv"
)


date = pd.read_csv(
    "dim_date.csv"
)



# =====================================================
# PARAMETER
# =====================================================


TOTAL_CAMPAIGN = 50000



# =====================================================
# PRODUCT WEIGHT
# =====================================================


category_weight = {


    "Food":0.90,

    "Beverage":0.85,

    "Fabric Care":0.80,

    "Snack":0.70,

    "Home Care":0.60,

    "Personal Care":0.50,

    "Baby Care":0.40

}



product["campaign_weight"] = (

    product["category"]

    .map(category_weight)

    .fillna(0.5)

)



# =====================================================
# PLATFORM
# =====================================================


platform_rule = {


    "TikTok":25,

    "Shopee Ads":20,

    "Instagram":15,

    "Facebook":10,

    "Google Ads":10,

    "YouTube":10,

    "Tokopedia Ads":10

}



platforms=list(
    platform_rule.keys()
)


platform_weights=list(
    platform_rule.values()
)



# =====================================================
# CAMPAIGN TYPE
# =====================================================


campaign_types=[

    "Brand Awareness",

    "Product Launch",

    "Promo Campaign",

    "Ramadan Campaign",

    "11.11 Campaign",

    "12.12 Campaign",

    "Influencer Campaign",

    "Flash Sale Campaign"

]



# =====================================================
# GENERATE
# =====================================================


campaign=[]



for i in range(
    TOTAL_CAMPAIGN
):


    # Product

    sku = product.sample(

        1,

        weights=product["campaign_weight"]

    ).iloc[0]



    # Platform

    platform=random.choices(

        platforms,

        weights=platform_weights

    )[0]



    # Campaign Type

    campaign_type=random.choice(

        campaign_types

    )



    # Date

    start=pd.to_datetime(

        date.sample(1)["date"].values[0]

    )



    # Duration

    if campaign_type=="Flash Sale Campaign":

        duration=random.randint(
            1,
            7
        )


    elif campaign_type=="Brand Awareness":

        duration=random.randint(
            30,
            90
        )


    else:

        duration=random.randint(
            7,
            60
        )



    end=start+timedelta(
        days=duration
    )



    if end.year > 2026:

        continue



    # Spend

    spend=random.randint(

        5000000,

        1000000000

    )



    # Impression

    impressions=random.randint(

        10000,

        20000000

    )



    # CTR

    if platform in [

        "Shopee Ads",

        "Tokopedia Ads",

        "Google Ads"

    ]:


        ctr=random.uniform(

            0.02,

            0.08

        )


    else:


        ctr=random.uniform(

            0.005,

            0.03

        )



    clicks=int(

        impressions*ctr

    )



    # Engagement

    engagement=int(

        impressions*

        random.uniform(

            0.01,

            0.10

        )

    )



    # Conversion

    conversion=random.uniform(

        0.01,

        0.08

    )



    campaign.append([


        f"CMP{i+1:06d}",


        sku["sku_id"],


        platform,


        campaign_type,


        start.date(),


        end.date(),


        spend,


        impressions,


        clicks,


        engagement,


        round(

            ctr*100,

            2

        ),


        round(

            conversion*100,

            2

        )


    ])




# =====================================================
# DATAFRAME
# =====================================================


fact_campaign=pd.DataFrame(

    campaign,

    columns=[

        "campaign_id",

        "sku_id",

        "platform",

        "campaign_type",

        "start_date",

        "end_date",

        "spend",

        "impressions",

        "clicks",

        "engagement",

        "ctr",

        "conversion_rate"

    ]

)



# =====================================================
# VALIDATION
# =====================================================


print(
    fact_campaign.head()
)


print(
    "\nTotal Campaign:",
    len(fact_campaign)
)



print(

    "\nPlatform Distribution:"

)


print(

    fact_campaign["platform"]

    .value_counts()

)



# =====================================================
# EXPORT
# =====================================================


fact_campaign.to_csv(

    "fact_digital_campaign.csv",

    index=False

)



print(

    "\nFile berhasil dibuat: fact_digital_campaign.csv"

)

  campaign_id               sku_id  platform        campaign_type  start_date  \
0   CMP000001      SYSTEMA-GEN-001  Facebook      Brand Awareness  2026-03-22
1   CMP000002       SOKLIN-GEN-001   YouTube       Product Launch  2023-04-01
2   CMP000003    FROSTBITE-ICE-001    TikTok     Ramadan Campaign  2025-07-28
3   CMP000004  SEGARDINGIN-GEN-001   YouTube       Promo Campaign  2024-01-08
4   CMP000005   HERSPROTEX-GEN-001    TikTok  Influencer Campaign  2026-11-25

     end_date      spend  impressions  clicks  engagement   ctr  \
0  2026-06-07  300310485      8227207   87046      627591  1.06
1  2023-05-15  458035110      1076449    6184       31946  0.57
2  2025-09-18  702808098     18295201  283355      922605  1.55
3  2024-02-28  458778756     11426912  136514      335702  1.19
4  2026-12-08  390451171     11551238  232100      954612  2.01

   conversion_rate
0             5.74
1             4.54
2             2.95
3             6.34
4             6.11

Total Campaign: 48844

Platform Distribution:
platform
TikTok           12139
Shopee Ads        9800
Instagram         7280
YouTube           4948
Facebook          4914
Google Ads        4888
Tokopedia Ads     4875
Name: count, dtype: int64

File berhasil dibuat: fact_digital_campaign.csv